/*
 * testmessage360simpl2_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/03/2016
 */
package transcription_pkg


import(
	"testmessage360simpl2_lib/models_pkg"
	"github.com/apimatic/unirest-go"
	"testmessage360simpl2_lib"
	"testmessage360simpl2_lib/apihelper_pkg"
)
/*
 * Client structure as interface implementation
 */
type TRANSCRIPTION_IMPL struct { }

/**
 * View Particular Transcription JSON Response
 * @param    string        transcriptionSid     parameter: Required
 * @return	Returns the string response from the API call
 */
func (me *TRANSCRIPTION_IMPL) CreateViewTranscriptionJSON (
            transcriptionSid string) (string, error) {
        //the base uri for api requests
    _queryBuilder := testmessage360simpl2_lib.BASEURI;

    //prepare query string for API call
   _queryBuilder = _queryBuilder + "/transcriptions/viewtranscription.json"

    //variable to hold errors
    var err error = nil
    //validate and preprocess url
    _queryBuilder, err = apihelper_pkg.CleanUrl(_queryBuilder)
    if err != nil {
        //error in url validation or cleaning
        return "", err
    }

    //prepare headers for the outgoing request
    headers := map[string]interface{} {
        "user-agent" : "APIMATIC 2.0",
    }

    //form parameters
    parameters := map[string]interface{} {

        "TranscriptionSid" : transcriptionSid,

    }


    //prepare API request
    _request := unirest.PostWithAuth(_queryBuilder, headers, parameters, testmessage360simpl2_lib.Config.AccountSid, testmessage360simpl2_lib.Config.AuthToken)
    //and invoke the API call request to fetch the response
    _response, err := unirest.AsString(_request);
    if err != nil {
        //error in API invocation
        return "", err
    }

    //error handling using HTTP status codes
    if (_response.Code < 200) || (_response.Code > 206) { //[200,206] = HTTP OK
        err = apihelper_pkg.NewAPIError("HTTP Response Not OK" , _response.Code, _response.RawBody)
    }
    if(err != nil) {
        //error detected in status code validation
        return "", err
    }

    //returning the response
    return _response.Body, nil
}

/**
 * View Particular Transcription XML Response
 * @param    string        transcriptionSid     parameter: Required
 * @return	Returns the string response from the API call
 */
func (me *TRANSCRIPTION_IMPL) CreateViewTranscriptionXML (
            transcriptionSid string) (string, error) {
        //the base uri for api requests
    _queryBuilder := testmessage360simpl2_lib.BASEURI;

    //prepare query string for API call
   _queryBuilder = _queryBuilder + "/transcriptions/viewtranscription.xml"

    //variable to hold errors
    var err error = nil
    //validate and preprocess url
    _queryBuilder, err = apihelper_pkg.CleanUrl(_queryBuilder)
    if err != nil {
        //error in url validation or cleaning
        return "", err
    }

    //prepare headers for the outgoing request
    headers := map[string]interface{} {
        "user-agent" : "APIMATIC 2.0",
    }

    //form parameters
    parameters := map[string]interface{} {

        "TranscriptionSid" : transcriptionSid,

    }


    //prepare API request
    _request := unirest.PostWithAuth(_queryBuilder, headers, parameters, testmessage360simpl2_lib.Config.AccountSid, testmessage360simpl2_lib.Config.AuthToken)
    //and invoke the API call request to fetch the response
    _response, err := unirest.AsString(_request);
    if err != nil {
        //error in API invocation
        return "", err
    }

    //error handling using HTTP status codes
    if (_response.Code < 200) || (_response.Code > 206) { //[200,206] = HTTP OK
        err = apihelper_pkg.NewAPIError("HTTP Response Not OK" , _response.Code, _response.RawBody)
    }
    if(err != nil) {
        //error detected in status code validation
        return "", err
    }

    //returning the response
    return _response.Body, nil
}

/**
 * Audio URL Transcription JSON
 * @param    string        audioUrl     parameter: Required
 * @return	Returns the string response from the API call
 */
func (me *TRANSCRIPTION_IMPL) CreateAudioURLTranscriptionJSON (
            audioUrl string) (string, error) {
        //the base uri for api requests
    _queryBuilder := testmessage360simpl2_lib.BASEURI;

    //prepare query string for API call
   _queryBuilder = _queryBuilder + "/transcriptions/audiourltranscription.json"

    //variable to hold errors
    var err error = nil
    //validate and preprocess url
    _queryBuilder, err = apihelper_pkg.CleanUrl(_queryBuilder)
    if err != nil {
        //error in url validation or cleaning
        return "", err
    }

    //prepare headers for the outgoing request
    headers := map[string]interface{} {
        "user-agent" : "APIMATIC 2.0",
    }

    //form parameters
    parameters := map[string]interface{} {

        "AudioUrl" : audioUrl,

    }


    //prepare API request
    _request := unirest.PostWithAuth(_queryBuilder, headers, parameters, testmessage360simpl2_lib.Config.AccountSid, testmessage360simpl2_lib.Config.AuthToken)
    //and invoke the API call request to fetch the response
    _response, err := unirest.AsString(_request);
    if err != nil {
        //error in API invocation
        return "", err
    }

    //error handling using HTTP status codes
    if (_response.Code < 200) || (_response.Code > 206) { //[200,206] = HTTP OK
        err = apihelper_pkg.NewAPIError("HTTP Response Not OK" , _response.Code, _response.RawBody)
    }
    if(err != nil) {
        //error detected in status code validation
        return "", err
    }

    //returning the response
    return _response.Body, nil
}

/**
 * Audio URL Transcription XML
 * @param    string        audioUrl     parameter: Required
 * @return	Returns the string response from the API call
 */
func (me *TRANSCRIPTION_IMPL) CreateAudioURLTranscriptionXML (
            audioUrl string) (string, error) {
        //the base uri for api requests
    _queryBuilder := testmessage360simpl2_lib.BASEURI;

    //prepare query string for API call
   _queryBuilder = _queryBuilder + "/transcriptions/audiourltranscription.xml"

    //variable to hold errors
    var err error = nil
    //validate and preprocess url
    _queryBuilder, err = apihelper_pkg.CleanUrl(_queryBuilder)
    if err != nil {
        //error in url validation or cleaning
        return "", err
    }

    //prepare headers for the outgoing request
    headers := map[string]interface{} {
        "user-agent" : "APIMATIC 2.0",
    }

    //form parameters
    parameters := map[string]interface{} {

        "AudioUrl" : audioUrl,

    }


    //prepare API request
    _request := unirest.PostWithAuth(_queryBuilder, headers, parameters, testmessage360simpl2_lib.Config.AccountSid, testmessage360simpl2_lib.Config.AuthToken)
    //and invoke the API call request to fetch the response
    _response, err := unirest.AsString(_request);
    if err != nil {
        //error in API invocation
        return "", err
    }

    //error handling using HTTP status codes
    if (_response.Code < 200) || (_response.Code > 206) { //[200,206] = HTTP OK
        err = apihelper_pkg.NewAPIError("HTTP Response Not OK" , _response.Code, _response.RawBody)
    }
    if(err != nil) {
        //error detected in status code validation
        return "", err
    }

    //returning the response
    return _response.Body, nil
}

/**
 * Recording Transcription JSON
 * @param    string        recordingSid     parameter: Required
 * @return	Returns the string response from the API call
 */
func (me *TRANSCRIPTION_IMPL) CreateRecordingTranscriptionJSON (
            recordingSid string) (string, error) {
        //the base uri for api requests
    _queryBuilder := testmessage360simpl2_lib.BASEURI;

    //prepare query string for API call
   _queryBuilder = _queryBuilder + "/transcriptions/recordingtranscription.json"

    //variable to hold errors
    var err error = nil
    //validate and preprocess url
    _queryBuilder, err = apihelper_pkg.CleanUrl(_queryBuilder)
    if err != nil {
        //error in url validation or cleaning
        return "", err
    }

    //prepare headers for the outgoing request
    headers := map[string]interface{} {
        "user-agent" : "APIMATIC 2.0",
    }

    //form parameters
    parameters := map[string]interface{} {

        "RecordingSid" : recordingSid,

    }


    //prepare API request
    _request := unirest.PostWithAuth(_queryBuilder, headers, parameters, testmessage360simpl2_lib.Config.AccountSid, testmessage360simpl2_lib.Config.AuthToken)
    //and invoke the API call request to fetch the response
    _response, err := unirest.AsString(_request);
    if err != nil {
        //error in API invocation
        return "", err
    }

    //error handling using HTTP status codes
    if (_response.Code < 200) || (_response.Code > 206) { //[200,206] = HTTP OK
        err = apihelper_pkg.NewAPIError("HTTP Response Not OK" , _response.Code, _response.RawBody)
    }
    if(err != nil) {
        //error detected in status code validation
        return "", err
    }

    //returning the response
    return _response.Body, nil
}

/**
 * Recording Transcription XML
 * @param    string        recordingSid     parameter: Required
 * @return	Returns the string response from the API call
 */
func (me *TRANSCRIPTION_IMPL) CreateRecordingTranscriptionXML (
            recordingSid string) (string, error) {
        //the base uri for api requests
    _queryBuilder := testmessage360simpl2_lib.BASEURI;

    //prepare query string for API call
   _queryBuilder = _queryBuilder + "/transcriptions/recordingtranscription.xml"

    //variable to hold errors
    var err error = nil
    //validate and preprocess url
    _queryBuilder, err = apihelper_pkg.CleanUrl(_queryBuilder)
    if err != nil {
        //error in url validation or cleaning
        return "", err
    }

    //prepare headers for the outgoing request
    headers := map[string]interface{} {
        "user-agent" : "APIMATIC 2.0",
    }

    //form parameters
    parameters := map[string]interface{} {

        "RecordingSid" : recordingSid,

    }


    //prepare API request
    _request := unirest.PostWithAuth(_queryBuilder, headers, parameters, testmessage360simpl2_lib.Config.AccountSid, testmessage360simpl2_lib.Config.AuthToken)
    //and invoke the API call request to fetch the response
    _response, err := unirest.AsString(_request);
    if err != nil {
        //error in API invocation
        return "", err
    }

    //error handling using HTTP status codes
    if (_response.Code < 200) || (_response.Code > 206) { //[200,206] = HTTP OK
        err = apihelper_pkg.NewAPIError("HTTP Response Not OK" , _response.Code, _response.RawBody)
    }
    if(err != nil) {
        //error detected in status code validation
        return "", err
    }

    //returning the response
    return _response.Body, nil
}

/**
 * Get All transcription in JSON response
 * @param    *int64                       page                parameter: Optional
 * @param    *int64                       pageSize            parameter: Optional
 * @param    models_pkg.StatusEnum        status              parameter: Optional
 * @param    *string                      dateTranscribed     parameter: Optional
 * @return	Returns the string response from the API call
 */
func (me *TRANSCRIPTION_IMPL) CreateListTranscriptionJSON (
            page *int64,
            pageSize *int64,
            status models_pkg.StatusEnum,
            dateTranscribed *string) (string, error) {
        //the base uri for api requests
    _queryBuilder := testmessage360simpl2_lib.BASEURI;

    //prepare query string for API call
   _queryBuilder = _queryBuilder + "/transcriptions/listtranscription.json"

    //variable to hold errors
    var err error = nil
    //validate and preprocess url
    _queryBuilder, err = apihelper_pkg.CleanUrl(_queryBuilder)
    if err != nil {
        //error in url validation or cleaning
        return "", err
    }

    //prepare headers for the outgoing request
    headers := map[string]interface{} {
        "user-agent" : "APIMATIC 2.0",
    }

    //form parameters
    parameters := map[string]interface{} {

        "Page" : page,
        "PageSize" : pageSize,
        "Status" : models_pkg.StatusEnumToValue(status),
        "DateTranscribed" : dateTranscribed,

    }


    //prepare API request
    _request := unirest.PostWithAuth(_queryBuilder, headers, parameters, testmessage360simpl2_lib.Config.AccountSid, testmessage360simpl2_lib.Config.AuthToken)
    //and invoke the API call request to fetch the response
    _response, err := unirest.AsString(_request);
    if err != nil {
        //error in API invocation
        return "", err
    }

    //error handling using HTTP status codes
    if (_response.Code < 200) || (_response.Code > 206) { //[200,206] = HTTP OK
        err = apihelper_pkg.NewAPIError("HTTP Response Not OK" , _response.Code, _response.RawBody)
    }
    if(err != nil) {
        //error detected in status code validation
        return "", err
    }

    //returning the response
    return _response.Body, nil
}

/**
 * Get All transcription in XML response
 * @param    *int64                       page                parameter: Optional
 * @param    *int64                       pageSize            parameter: Optional
 * @param    models_pkg.StatusEnum        status              parameter: Optional
 * @param    *string                      dateTranscribed     parameter: Optional
 * @return	Returns the string response from the API call
 */
func (me *TRANSCRIPTION_IMPL) CreateListTranscriptionXML (
            page *int64,
            pageSize *int64,
            status models_pkg.StatusEnum,
            dateTranscribed *string) (string, error) {
        //the base uri for api requests
    _queryBuilder := testmessage360simpl2_lib.BASEURI;

    //prepare query string for API call
   _queryBuilder = _queryBuilder + "/transcriptions/listtranscription.xml"

    //variable to hold errors
    var err error = nil
    //validate and preprocess url
    _queryBuilder, err = apihelper_pkg.CleanUrl(_queryBuilder)
    if err != nil {
        //error in url validation or cleaning
        return "", err
    }

    //prepare headers for the outgoing request
    headers := map[string]interface{} {
        "user-agent" : "APIMATIC 2.0",
    }

    //form parameters
    parameters := map[string]interface{} {

        "Page" : page,
        "PageSize" : pageSize,
        "Status" : models_pkg.StatusEnumToValue(status),
        "DateTranscribed" : dateTranscribed,

    }


    //prepare API request
    _request := unirest.PostWithAuth(_queryBuilder, headers, parameters, testmessage360simpl2_lib.Config.AccountSid, testmessage360simpl2_lib.Config.AuthToken)
    //and invoke the API call request to fetch the response
    _response, err := unirest.AsString(_request);
    if err != nil {
        //error in API invocation
        return "", err
    }

    //error handling using HTTP status codes
    if (_response.Code < 200) || (_response.Code > 206) { //[200,206] = HTTP OK
        err = apihelper_pkg.NewAPIError("HTTP Response Not OK" , _response.Code, _response.RawBody)
    }
    if(err != nil) {
        //error detected in status code validation
        return "", err
    }

    //returning the response
    return _response.Body, nil
}

