/*
 * testmessage360simpl2_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/03/2016
 */

package transcription_pkg

import "testmessage360simpl2_lib/models_pkg"

/*
 * Interface for the TRANSCRIPTION_IMPL
 */
type TRANSCRIPTION interface {
    CreateViewTranscriptionJSON (string) (string, error)

    CreateViewTranscriptionXML (string) (string, error)

    CreateAudioURLTranscriptionJSON (string) (string, error)

    CreateAudioURLTranscriptionXML (string) (string, error)

    CreateRecordingTranscriptionJSON (string) (string, error)

    CreateRecordingTranscriptionXML (string) (string, error)

    CreateListTranscriptionJSON (*int64, *int64, models_pkg.StatusEnum, *string) (string, error)

    CreateListTranscriptionXML (*int64, *int64, models_pkg.StatusEnum, *string) (string, error)
}

/*
 * Factory for the TRANSCRIPTION interaface returning TRANSCRIPTION_IMPL
 */
func NewTRANSCRIPTION() TRANSCRIPTION {
    return &TRANSCRIPTION_IMPL{}
}