/*
 * testmessage360simpl2_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/03/2016
 */

package usage_pkg


/*
 * Interface for the USAGE_IMPL
 */
type USAGE interface {
    CreateListUsage (string, string, string) (string, error)
}

/*
 * Factory for the USAGE interaface returning USAGE_IMPL
 */
func NewUSAGE() USAGE {
    return &USAGE_IMPL{}
}