/*
 * testmessage360simpl2_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/03/2016
 */

package recording_pkg


/*
 * Interface for the RECORDING_IMPL
 */
type RECORDING interface {
    CreateViewRecordingJSON (string) (string, error)

    CreateViewRecordingXML (string) (string, error)

    CreateDeleteRecordingJSON (string) (string, error)

    CreateDeleteRecordingXML (string) (string, error)

    CreateListRecordingXML (*int64, *int64, *string, *string) (string, error)

    CreateListRecordingJSON (*int64, *int64, *string, *string) (string, error)
}

/*
 * Factory for the RECORDING interaface returning RECORDING_IMPL
 */
func NewRECORDING() RECORDING {
    return &RECORDING_IMPL{}
}