/*
 * testmessage360simpl2_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/03/2016
 */
package phonenumber_pkg


import(
	"testmessage360simpl2_lib/models_pkg"
	"github.com/apimatic/unirest-go"
	"testmessage360simpl2_lib"
	"testmessage360simpl2_lib/apihelper_pkg"
)
/*
 * Client structure as interface implementation
 */
type PHONENUMBER_IMPL struct { }

/**
 * Get Phone Number Details JSON
 * @param    string        phoneNumber     parameter: Required
 * @return	Returns the string response from the API call
 */
func (me *PHONENUMBER_IMPL) CreateViewNumberDetailsJSON (
            phoneNumber string) (string, error) {
        //the base uri for api requests
    _queryBuilder := testmessage360simpl2_lib.BASEURI;

    //prepare query string for API call
   _queryBuilder = _queryBuilder + "/incomingphone/viewnumber.json"

    //variable to hold errors
    var err error = nil
    //validate and preprocess url
    _queryBuilder, err = apihelper_pkg.CleanUrl(_queryBuilder)
    if err != nil {
        //error in url validation or cleaning
        return "", err
    }

    //prepare headers for the outgoing request
    headers := map[string]interface{} {
        "user-agent" : "APIMATIC 2.0",
    }

    //form parameters
    parameters := map[string]interface{} {

        "PhoneNumber" : phoneNumber,

    }


    //prepare API request
    _request := unirest.PostWithAuth(_queryBuilder, headers, parameters, testmessage360simpl2_lib.Config.AccountSid, testmessage360simpl2_lib.Config.AuthToken)
    //and invoke the API call request to fetch the response
    _response, err := unirest.AsString(_request);
    if err != nil {
        //error in API invocation
        return "", err
    }

    //error handling using HTTP status codes
    if (_response.Code < 200) || (_response.Code > 206) { //[200,206] = HTTP OK
        err = apihelper_pkg.NewAPIError("HTTP Response Not OK" , _response.Code, _response.RawBody)
    }
    if(err != nil) {
        //error detected in status code validation
        return "", err
    }

    //returning the response
    return _response.Body, nil
}

/**
 * Get Phone Number Details XML
 * @param    string        phoneNumber     parameter: Required
 * @return	Returns the string response from the API call
 */
func (me *PHONENUMBER_IMPL) CreateViewPhoneNumberXML (
            phoneNumber string) (string, error) {
        //the base uri for api requests
    _queryBuilder := testmessage360simpl2_lib.BASEURI;

    //prepare query string for API call
   _queryBuilder = _queryBuilder + "/incomingphone/viewnumber.xml"

    //variable to hold errors
    var err error = nil
    //validate and preprocess url
    _queryBuilder, err = apihelper_pkg.CleanUrl(_queryBuilder)
    if err != nil {
        //error in url validation or cleaning
        return "", err
    }

    //prepare headers for the outgoing request
    headers := map[string]interface{} {
        "user-agent" : "APIMATIC 2.0",
    }

    //form parameters
    parameters := map[string]interface{} {

        "PhoneNumber" : phoneNumber,

    }


    //prepare API request
    _request := unirest.PostWithAuth(_queryBuilder, headers, parameters, testmessage360simpl2_lib.Config.AccountSid, testmessage360simpl2_lib.Config.AuthToken)
    //and invoke the API call request to fetch the response
    _response, err := unirest.AsString(_request);
    if err != nil {
        //error in API invocation
        return "", err
    }

    //error handling using HTTP status codes
    if (_response.Code < 200) || (_response.Code > 206) { //[200,206] = HTTP OK
        err = apihelper_pkg.NewAPIError("HTTP Response Not OK" , _response.Code, _response.RawBody)
    }
    if(err != nil) {
        //error detected in status code validation
        return "", err
    }

    //returning the response
    return _response.Body, nil
}

/**
 * Buy Phone Number 
 * @param    string        phoneNumber     parameter: Required
 * @return	Returns the string response from the API call
 */
func (me *PHONENUMBER_IMPL) CreateBuyNumberJSON (
            phoneNumber string) (string, error) {
        //the base uri for api requests
    _queryBuilder := testmessage360simpl2_lib.BASEURI;

    //prepare query string for API call
   _queryBuilder = _queryBuilder + "/incomingphone/buynumber.json"

    //variable to hold errors
    var err error = nil
    //validate and preprocess url
    _queryBuilder, err = apihelper_pkg.CleanUrl(_queryBuilder)
    if err != nil {
        //error in url validation or cleaning
        return "", err
    }

    //prepare headers for the outgoing request
    headers := map[string]interface{} {
        "user-agent" : "APIMATIC 2.0",
    }

    //form parameters
    parameters := map[string]interface{} {

        "PhoneNumber" : phoneNumber,

    }


    //prepare API request
    _request := unirest.PostWithAuth(_queryBuilder, headers, parameters, testmessage360simpl2_lib.Config.AccountSid, testmessage360simpl2_lib.Config.AuthToken)
    //and invoke the API call request to fetch the response
    _response, err := unirest.AsString(_request);
    if err != nil {
        //error in API invocation
        return "", err
    }

    //error handling using HTTP status codes
    if (_response.Code < 200) || (_response.Code > 206) { //[200,206] = HTTP OK
        err = apihelper_pkg.NewAPIError("HTTP Response Not OK" , _response.Code, _response.RawBody)
    }
    if(err != nil) {
        //error detected in status code validation
        return "", err
    }

    //returning the response
    return _response.Body, nil
}

/**
 * Buy Phone Number 
 * @param    string        phoneNumber     parameter: Required
 * @return	Returns the string response from the API call
 */
func (me *PHONENUMBER_IMPL) CreateBuyNumberXML (
            phoneNumber string) (string, error) {
        //the base uri for api requests
    _queryBuilder := testmessage360simpl2_lib.BASEURI;

    //prepare query string for API call
   _queryBuilder = _queryBuilder + "/incomingphone/buynumber.xml"

    //variable to hold errors
    var err error = nil
    //validate and preprocess url
    _queryBuilder, err = apihelper_pkg.CleanUrl(_queryBuilder)
    if err != nil {
        //error in url validation or cleaning
        return "", err
    }

    //prepare headers for the outgoing request
    headers := map[string]interface{} {
        "user-agent" : "APIMATIC 2.0",
    }

    //form parameters
    parameters := map[string]interface{} {

        "PhoneNumber" : phoneNumber,

    }


    //prepare API request
    _request := unirest.PostWithAuth(_queryBuilder, headers, parameters, testmessage360simpl2_lib.Config.AccountSid, testmessage360simpl2_lib.Config.AuthToken)
    //and invoke the API call request to fetch the response
    _response, err := unirest.AsString(_request);
    if err != nil {
        //error in API invocation
        return "", err
    }

    //error handling using HTTP status codes
    if (_response.Code < 200) || (_response.Code > 206) { //[200,206] = HTTP OK
        err = apihelper_pkg.NewAPIError("HTTP Response Not OK" , _response.Code, _response.RawBody)
    }
    if(err != nil) {
        //error detected in status code validation
        return "", err
    }

    //returning the response
    return _response.Body, nil
}

/**
 * Release number from account JSON
 * @param    string        phoneNumber     parameter: Required
 * @return	Returns the string response from the API call
 */
func (me *PHONENUMBER_IMPL) CreateReleaseNumberJson (
            phoneNumber string) (string, error) {
        //the base uri for api requests
    _queryBuilder := testmessage360simpl2_lib.BASEURI;

    //prepare query string for API call
   _queryBuilder = _queryBuilder + "/incomingphone/releasenumber.json"

    //variable to hold errors
    var err error = nil
    //validate and preprocess url
    _queryBuilder, err = apihelper_pkg.CleanUrl(_queryBuilder)
    if err != nil {
        //error in url validation or cleaning
        return "", err
    }

    //prepare headers for the outgoing request
    headers := map[string]interface{} {
        "user-agent" : "APIMATIC 2.0",
    }

    //form parameters
    parameters := map[string]interface{} {

        "PhoneNumber" : phoneNumber,

    }


    //prepare API request
    _request := unirest.PostWithAuth(_queryBuilder, headers, parameters, testmessage360simpl2_lib.Config.AccountSid, testmessage360simpl2_lib.Config.AuthToken)
    //and invoke the API call request to fetch the response
    _response, err := unirest.AsString(_request);
    if err != nil {
        //error in API invocation
        return "", err
    }

    //error handling using HTTP status codes
    if (_response.Code < 200) || (_response.Code > 206) { //[200,206] = HTTP OK
        err = apihelper_pkg.NewAPIError("HTTP Response Not OK" , _response.Code, _response.RawBody)
    }
    if(err != nil) {
        //error detected in status code validation
        return "", err
    }

    //returning the response
    return _response.Body, nil
}

/**
 * Release number from account JSON
 * @param    string        phoneNumber     parameter: Required
 * @return	Returns the string response from the API call
 */
func (me *PHONENUMBER_IMPL) CreateReleaseNumberXML (
            phoneNumber string) (string, error) {
        //the base uri for api requests
    _queryBuilder := testmessage360simpl2_lib.BASEURI;

    //prepare query string for API call
   _queryBuilder = _queryBuilder + "/incomingphone/releasenumber.xml"

    //variable to hold errors
    var err error = nil
    //validate and preprocess url
    _queryBuilder, err = apihelper_pkg.CleanUrl(_queryBuilder)
    if err != nil {
        //error in url validation or cleaning
        return "", err
    }

    //prepare headers for the outgoing request
    headers := map[string]interface{} {
        "user-agent" : "APIMATIC 2.0",
    }

    //form parameters
    parameters := map[string]interface{} {

        "PhoneNumber" : phoneNumber,

    }


    //prepare API request
    _request := unirest.PostWithAuth(_queryBuilder, headers, parameters, testmessage360simpl2_lib.Config.AccountSid, testmessage360simpl2_lib.Config.AuthToken)
    //and invoke the API call request to fetch the response
    _response, err := unirest.AsString(_request);
    if err != nil {
        //error in API invocation
        return "", err
    }

    //error handling using HTTP status codes
    if (_response.Code < 200) || (_response.Code > 206) { //[200,206] = HTTP OK
        err = apihelper_pkg.NewAPIError("HTTP Response Not OK" , _response.Code, _response.RawBody)
    }
    if(err != nil) {
        //error detected in status code validation
        return "", err
    }

    //returning the response
    return _response.Body, nil
}

/**
 * Available Phone Number XML
 * @param    string        numberType     parameter: Required
 * @param    string        areaCode       parameter: Required
 * @param    *int64        pageSize       parameter: Optional
 * @return	Returns the string response from the API call
 */
func (me *PHONENUMBER_IMPL) CreateAvailablePhoneNumberXML (
            numberType string,
            areaCode string,
            pageSize *int64) (string, error) {
        //the base uri for api requests
    _queryBuilder := testmessage360simpl2_lib.BASEURI;

    //prepare query string for API call
   _queryBuilder = _queryBuilder + "/incomingphone/availablenumber.xml"

    //variable to hold errors
    var err error = nil
    //validate and preprocess url
    _queryBuilder, err = apihelper_pkg.CleanUrl(_queryBuilder)
    if err != nil {
        //error in url validation or cleaning
        return "", err
    }

    //prepare headers for the outgoing request
    headers := map[string]interface{} {
        "user-agent" : "APIMATIC 2.0",
    }

    //form parameters
    parameters := map[string]interface{} {

        "NumberType" : numberType,
        "AreaCode" : areaCode,
        "PageSize" : pageSize,

    }


    //prepare API request
    _request := unirest.PostWithAuth(_queryBuilder, headers, parameters, testmessage360simpl2_lib.Config.AccountSid, testmessage360simpl2_lib.Config.AuthToken)
    //and invoke the API call request to fetch the response
    _response, err := unirest.AsString(_request);
    if err != nil {
        //error in API invocation
        return "", err
    }

    //error handling using HTTP status codes
    if (_response.Code < 200) || (_response.Code > 206) { //[200,206] = HTTP OK
        err = apihelper_pkg.NewAPIError("HTTP Response Not OK" , _response.Code, _response.RawBody)
    }
    if(err != nil) {
        //error detected in status code validation
        return "", err
    }

    //returning the response
    return _response.Body, nil
}

/**
 * List Account's Phone number details json
 * @param    *int64         page             parameter: Optional
 * @param    *int64         pageSize         parameter: Optional
 * @param    *string        numberType       parameter: Optional
 * @param    *string        friendlyName     parameter: Optional
 * @return	Returns the string response from the API call
 */
func (me *PHONENUMBER_IMPL) CreateListNumberJSON (
            page *int64,
            pageSize *int64,
            numberType *string,
            friendlyName *string) (string, error) {
        //the base uri for api requests
    _queryBuilder := testmessage360simpl2_lib.BASEURI;

    //prepare query string for API call
   _queryBuilder = _queryBuilder + "/incomingphone/listnumber.json"

    //variable to hold errors
    var err error = nil
    //validate and preprocess url
    _queryBuilder, err = apihelper_pkg.CleanUrl(_queryBuilder)
    if err != nil {
        //error in url validation or cleaning
        return "", err
    }

    //prepare headers for the outgoing request
    headers := map[string]interface{} {
        "user-agent" : "APIMATIC 2.0",
    }

    //form parameters
    parameters := map[string]interface{} {

        "Page" : page,
        "PageSize" : pageSize,
        "NumberType" : numberType,
        "FriendlyName" : friendlyName,

    }


    //prepare API request
    _request := unirest.PostWithAuth(_queryBuilder, headers, parameters, testmessage360simpl2_lib.Config.AccountSid, testmessage360simpl2_lib.Config.AuthToken)
    //and invoke the API call request to fetch the response
    _response, err := unirest.AsString(_request);
    if err != nil {
        //error in API invocation
        return "", err
    }

    //error handling using HTTP status codes
    if (_response.Code < 200) || (_response.Code > 206) { //[200,206] = HTTP OK
        err = apihelper_pkg.NewAPIError("HTTP Response Not OK" , _response.Code, _response.RawBody)
    }
    if(err != nil) {
        //error detected in status code validation
        return "", err
    }

    //returning the response
    return _response.Body, nil
}

/**
 * List Account's Phone number details XML
 * @param    *int64         page             parameter: Optional
 * @param    *int64         pageSize         parameter: Optional
 * @param    *string        numberType       parameter: Optional
 * @param    *string        friendlyName     parameter: Optional
 * @return	Returns the string response from the API call
 */
func (me *PHONENUMBER_IMPL) CreateListNumberXML (
            page *int64,
            pageSize *int64,
            numberType *string,
            friendlyName *string) (string, error) {
        //the base uri for api requests
    _queryBuilder := testmessage360simpl2_lib.BASEURI;

    //prepare query string for API call
   _queryBuilder = _queryBuilder + "/incomingphone/listnumber.xml"

    //variable to hold errors
    var err error = nil
    //validate and preprocess url
    _queryBuilder, err = apihelper_pkg.CleanUrl(_queryBuilder)
    if err != nil {
        //error in url validation or cleaning
        return "", err
    }

    //prepare headers for the outgoing request
    headers := map[string]interface{} {
        "user-agent" : "APIMATIC 2.0",
    }

    //form parameters
    parameters := map[string]interface{} {

        "Page" : page,
        "PageSize" : pageSize,
        "NumberType" : numberType,
        "FriendlyName" : friendlyName,

    }


    //prepare API request
    _request := unirest.PostWithAuth(_queryBuilder, headers, parameters, testmessage360simpl2_lib.Config.AccountSid, testmessage360simpl2_lib.Config.AuthToken)
    //and invoke the API call request to fetch the response
    _response, err := unirest.AsString(_request);
    if err != nil {
        //error in API invocation
        return "", err
    }

    //error handling using HTTP status codes
    if (_response.Code < 200) || (_response.Code > 206) { //[200,206] = HTTP OK
        err = apihelper_pkg.NewAPIError("HTTP Response Not OK" , _response.Code, _response.RawBody)
    }
    if(err != nil) {
        //error detected in status code validation
        return "", err
    }

    //returning the response
    return _response.Body, nil
}

/**
 * Available Phone Number Json
 * @param    string        numberType     parameter: Required
 * @param    string        areaCode       parameter: Required
 * @param    *int64        pageSize       parameter: Optional
 * @return	Returns the string response from the API call
 */
func (me *PHONENUMBER_IMPL) CreateAvailablePhoneNumberJson (
            numberType string,
            areaCode string,
            pageSize *int64) (string, error) {
        //the base uri for api requests
    _queryBuilder := testmessage360simpl2_lib.BASEURI;

    //prepare query string for API call
   _queryBuilder = _queryBuilder + "/incomingphone/availablenumber.json"

    //variable to hold errors
    var err error = nil
    //validate and preprocess url
    _queryBuilder, err = apihelper_pkg.CleanUrl(_queryBuilder)
    if err != nil {
        //error in url validation or cleaning
        return "", err
    }

    //prepare headers for the outgoing request
    headers := map[string]interface{} {
        "user-agent" : "APIMATIC 2.0",
    }

    //form parameters
    parameters := map[string]interface{} {

        "NumberType" : numberType,
        "AreaCode" : areaCode,
        "PageSize" : pageSize,

    }


    //prepare API request
    _request := unirest.PostWithAuth(_queryBuilder, headers, parameters, testmessage360simpl2_lib.Config.AccountSid, testmessage360simpl2_lib.Config.AuthToken)
    //and invoke the API call request to fetch the response
    _response, err := unirest.AsString(_request);
    if err != nil {
        //error in API invocation
        return "", err
    }

    //error handling using HTTP status codes
    if (_response.Code < 200) || (_response.Code > 206) { //[200,206] = HTTP OK
        err = apihelper_pkg.NewAPIError("HTTP Response Not OK" , _response.Code, _response.RawBody)
    }
    if(err != nil) {
        //error detected in status code validation
        return "", err
    }

    //returning the response
    return _response.Body, nil
}

/**
 * Update Phone Number Details XML
 * @param    string                           phoneNumber              parameter: Required
 * @param    *string                          friendlyName             parameter: Optional
 * @param    *string                          voiceUrl                 parameter: Optional
 * @param    models_pkg.HttpMethodEnum        voiceMethod              parameter: Optional
 * @param    *string                          voiceFallbackUrl         parameter: Optional
 * @param    models_pkg.HttpMethodEnum        voiceFallbackMethod      parameter: Optional
 * @param    *string                          hangupCallback           parameter: Optional
 * @param    models_pkg.HttpMethodEnum        hangupCallbackMethod     parameter: Optional
 * @param    *string                          heartbeatUrl             parameter: Optional
 * @param    models_pkg.HttpMethodEnum        heartbeatMethod          parameter: Optional
 * @param    *string                          smsUrl                   parameter: Optional
 * @param    models_pkg.HttpMethodEnum        smsMethod                parameter: Optional
 * @param    *string                          smsFallbackUrl           parameter: Optional
 * @param    models_pkg.HttpMethodEnum        smsFallbackMethod        parameter: Optional
 * @return	Returns the string response from the API call
 */
func (me *PHONENUMBER_IMPL) UpdatePhoneNumberXML (
            phoneNumber string,
            friendlyName *string,
            voiceUrl *string,
            voiceMethod models_pkg.HttpMethodEnum,
            voiceFallbackUrl *string,
            voiceFallbackMethod models_pkg.HttpMethodEnum,
            hangupCallback *string,
            hangupCallbackMethod models_pkg.HttpMethodEnum,
            heartbeatUrl *string,
            heartbeatMethod models_pkg.HttpMethodEnum,
            smsUrl *string,
            smsMethod models_pkg.HttpMethodEnum,
            smsFallbackUrl *string,
            smsFallbackMethod models_pkg.HttpMethodEnum) (string, error) {
        //the base uri for api requests
    _queryBuilder := testmessage360simpl2_lib.BASEURI;

    //prepare query string for API call
   _queryBuilder = _queryBuilder + "/incomingphone/updatenumber.xml"

    //variable to hold errors
    var err error = nil
    //validate and preprocess url
    _queryBuilder, err = apihelper_pkg.CleanUrl(_queryBuilder)
    if err != nil {
        //error in url validation or cleaning
        return "", err
    }

    //prepare headers for the outgoing request
    headers := map[string]interface{} {
        "user-agent" : "APIMATIC 2.0",
    }

    //form parameters
    parameters := map[string]interface{} {

        "PhoneNumber" : phoneNumber,
        "FriendlyName" : friendlyName,
        "VoiceUrl" : voiceUrl,
        "VoiceMethod" : models_pkg.HttpMethodEnumToValue(voiceMethod),
        "VoiceFallbackUrl" : voiceFallbackUrl,
        "VoiceFallbackMethod" : models_pkg.HttpMethodEnumToValue(voiceFallbackMethod),
        "HangupCallback" : hangupCallback,
        "HangupCallbackMethod" : models_pkg.HttpMethodEnumToValue(hangupCallbackMethod),
        "HeartbeatUrl" : heartbeatUrl,
        "HeartbeatMethod" : models_pkg.HttpMethodEnumToValue(heartbeatMethod),
        "SmsUrl" : smsUrl,
        "SmsMethod" : models_pkg.HttpMethodEnumToValue(smsMethod),
        "SmsFallbackUrl" : smsFallbackUrl,
        "SmsFallbackMethod" : models_pkg.HttpMethodEnumToValue(smsFallbackMethod),

    }


    //prepare API request
    _request := unirest.PostWithAuth(_queryBuilder, headers, parameters, testmessage360simpl2_lib.Config.AccountSid, testmessage360simpl2_lib.Config.AuthToken)
    //and invoke the API call request to fetch the response
    _response, err := unirest.AsString(_request);
    if err != nil {
        //error in API invocation
        return "", err
    }

    //error handling using HTTP status codes
    if (_response.Code < 200) || (_response.Code > 206) { //[200,206] = HTTP OK
        err = apihelper_pkg.NewAPIError("HTTP Response Not OK" , _response.Code, _response.RawBody)
    }
    if(err != nil) {
        //error detected in status code validation
        return "", err
    }

    //returning the response
    return _response.Body, nil
}

/**
 * Update Phone Number Details JSON
 * @param    string                           phoneNumberr             parameter: Required
 * @param    *string                          friendlyName             parameter: Optional
 * @param    *string                          voiceUrl                 parameter: Optional
 * @param    models_pkg.HttpMethodEnum        voiceMethod              parameter: Optional
 * @param    *string                          voiceFallbackUrl         parameter: Optional
 * @param    models_pkg.HttpMethodEnum        voiceFallbackMethod      parameter: Optional
 * @param    *string                          hangupCallback           parameter: Optional
 * @param    models_pkg.HttpMethodEnum        hangupCallbackMethod     parameter: Optional
 * @param    *string                          heartbeatUrl             parameter: Optional
 * @param    models_pkg.HttpMethodEnum        heartbeatMethod          parameter: Optional
 * @param    *string                          smsUrl                   parameter: Optional
 * @param    models_pkg.HttpMethodEnum        smsMethod                parameter: Optional
 * @param    *string                          smsFallbackUrl           parameter: Optional
 * @param    models_pkg.HttpMethodEnum        smsFallbackMethod        parameter: Optional
 * @return	Returns the string response from the API call
 */
func (me *PHONENUMBER_IMPL) UpdatePhoneNumberJSON (
            phoneNumberr string,
            friendlyName *string,
            voiceUrl *string,
            voiceMethod models_pkg.HttpMethodEnum,
            voiceFallbackUrl *string,
            voiceFallbackMethod models_pkg.HttpMethodEnum,
            hangupCallback *string,
            hangupCallbackMethod models_pkg.HttpMethodEnum,
            heartbeatUrl *string,
            heartbeatMethod models_pkg.HttpMethodEnum,
            smsUrl *string,
            smsMethod models_pkg.HttpMethodEnum,
            smsFallbackUrl *string,
            smsFallbackMethod models_pkg.HttpMethodEnum) (string, error) {
        //the base uri for api requests
    _queryBuilder := testmessage360simpl2_lib.BASEURI;

    //prepare query string for API call
   _queryBuilder = _queryBuilder + "/incomingphone/updatenumber.json"

    //variable to hold errors
    var err error = nil
    //validate and preprocess url
    _queryBuilder, err = apihelper_pkg.CleanUrl(_queryBuilder)
    if err != nil {
        //error in url validation or cleaning
        return "", err
    }

    //prepare headers for the outgoing request
    headers := map[string]interface{} {
        "user-agent" : "APIMATIC 2.0",
    }

    //form parameters
    parameters := map[string]interface{} {

        "PhoneNumberr" : phoneNumberr,
        "FriendlyName" : friendlyName,
        "VoiceUrl" : voiceUrl,
        "VoiceMethod" : models_pkg.HttpMethodEnumToValue(voiceMethod),
        "VoiceFallbackUrl" : voiceFallbackUrl,
        "VoiceFallbackMethod" : models_pkg.HttpMethodEnumToValue(voiceFallbackMethod),
        "HangupCallback" : hangupCallback,
        "HangupCallbackMethod" : models_pkg.HttpMethodEnumToValue(hangupCallbackMethod),
        "HeartbeatUrl" : heartbeatUrl,
        "HeartbeatMethod" : models_pkg.HttpMethodEnumToValue(heartbeatMethod),
        "SmsUrl" : smsUrl,
        "SmsMethod" : models_pkg.HttpMethodEnumToValue(smsMethod),
        "SmsFallbackUrl" : smsFallbackUrl,
        "SmsFallbackMethod" : models_pkg.HttpMethodEnumToValue(smsFallbackMethod),

    }


    //prepare API request
    _request := unirest.PostWithAuth(_queryBuilder, headers, parameters, testmessage360simpl2_lib.Config.AccountSid, testmessage360simpl2_lib.Config.AuthToken)
    //and invoke the API call request to fetch the response
    _response, err := unirest.AsString(_request);
    if err != nil {
        //error in API invocation
        return "", err
    }

    //error handling using HTTP status codes
    if (_response.Code < 200) || (_response.Code > 206) { //[200,206] = HTTP OK
        err = apihelper_pkg.NewAPIError("HTTP Response Not OK" , _response.Code, _response.RawBody)
    }
    if(err != nil) {
        //error detected in status code validation
        return "", err
    }

    //returning the response
    return _response.Body, nil
}

