/*
 * testmessage360simpl2_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/03/2016
 */

package phonenumber_pkg

import "testmessage360simpl2_lib/models_pkg"

/*
 * Interface for the PHONENUMBER_IMPL
 */
type PHONENUMBER interface {
    CreateViewNumberDetailsJSON (string) (string, error)

    CreateViewPhoneNumberXML (string) (string, error)

    CreateBuyNumberJSON (string) (string, error)

    CreateBuyNumberXML (string) (string, error)

    CreateReleaseNumberJson (string) (string, error)

    CreateReleaseNumberXML (string) (string, error)

    CreateAvailablePhoneNumberXML (string, string, *int64) (string, error)

    CreateListNumberJSON (*int64, *int64, *string, *string) (string, error)

    CreateListNumberXML (*int64, *int64, *string, *string) (string, error)

    CreateAvailablePhoneNumberJson (string, string, *int64) (string, error)

    UpdatePhoneNumberXML (string, *string, *string, models_pkg.HttpMethodEnum, *string, models_pkg.HttpMethodEnum, *string, models_pkg.HttpMethodEnum, *string, models_pkg.HttpMethodEnum, *string, models_pkg.HttpMethodEnum, *string, models_pkg.HttpMethodEnum) (string, error)

    UpdatePhoneNumberJSON (string, *string, *string, models_pkg.HttpMethodEnum, *string, models_pkg.HttpMethodEnum, *string, models_pkg.HttpMethodEnum, *string, models_pkg.HttpMethodEnum, *string, models_pkg.HttpMethodEnum, *string, models_pkg.HttpMethodEnum) (string, error)
}

/*
 * Factory for the PHONENUMBER interaface returning PHONENUMBER_IMPL
 */
func NewPHONENUMBER() PHONENUMBER {
    return &PHONENUMBER_IMPL{}
}