/*
 * testmessage360simpl2_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/03/2016
 */
package sms_pkg


import(
	"testmessage360simpl2_lib/models_pkg"
	"github.com/apimatic/unirest-go"
	"testmessage360simpl2_lib"
	"testmessage360simpl2_lib/apihelper_pkg"
)
/*
 * Client structure as interface implementation
 */
type SMS_IMPL struct { }

/**
 * View Particular SMS  XML Response
 * @param    string        messagesid     parameter: Required
 * @return	Returns the string response from the API call
 */
func (me *SMS_IMPL) CreateViewSMSXML (
            messagesid string) (string, error) {
        //the base uri for api requests
    _queryBuilder := testmessage360simpl2_lib.BASEURI;

    //prepare query string for API call
   _queryBuilder = _queryBuilder + "/sms/viewsms.xml"

    //variable to hold errors
    var err error = nil
    //validate and preprocess url
    _queryBuilder, err = apihelper_pkg.CleanUrl(_queryBuilder)
    if err != nil {
        //error in url validation or cleaning
        return "", err
    }

    //prepare headers for the outgoing request
    headers := map[string]interface{} {
        "user-agent" : "APIMATIC 2.0",
    }

    //form parameters
    parameters := map[string]interface{} {

        "messagesid" : messagesid,

    }


    //prepare API request
    _request := unirest.PostWithAuth(_queryBuilder, headers, parameters, testmessage360simpl2_lib.Config.AccountSid, testmessage360simpl2_lib.Config.AuthToken)
    //and invoke the API call request to fetch the response
    _response, err := unirest.AsString(_request);
    if err != nil {
        //error in API invocation
        return "", err
    }

    //error handling using HTTP status codes
    if (_response.Code < 200) || (_response.Code > 206) { //[200,206] = HTTP OK
        err = apihelper_pkg.NewAPIError("HTTP Response Not OK" , _response.Code, _response.RawBody)
    }
    if(err != nil) {
        //error detected in status code validation
        return "", err
    }

    //returning the response
    return _response.Body, nil
}

/**
 * View Particular SMS  JSON Response
 * @param    string        messagesid     parameter: Required
 * @return	Returns the string response from the API call
 */
func (me *SMS_IMPL) CreateViewSMSJSON (
            messagesid string) (string, error) {
        //the base uri for api requests
    _queryBuilder := testmessage360simpl2_lib.BASEURI;

    //prepare query string for API call
   _queryBuilder = _queryBuilder + "/sms/viewsms.json"

    //variable to hold errors
    var err error = nil
    //validate and preprocess url
    _queryBuilder, err = apihelper_pkg.CleanUrl(_queryBuilder)
    if err != nil {
        //error in url validation or cleaning
        return "", err
    }

    //prepare headers for the outgoing request
    headers := map[string]interface{} {
        "user-agent" : "APIMATIC 2.0",
    }

    //form parameters
    parameters := map[string]interface{} {

        "messagesid" : messagesid,

    }


    //prepare API request
    _request := unirest.PostWithAuth(_queryBuilder, headers, parameters, testmessage360simpl2_lib.Config.AccountSid, testmessage360simpl2_lib.Config.AuthToken)
    //and invoke the API call request to fetch the response
    _response, err := unirest.AsString(_request);
    if err != nil {
        //error in API invocation
        return "", err
    }

    //error handling using HTTP status codes
    if (_response.Code < 200) || (_response.Code > 206) { //[200,206] = HTTP OK
        err = apihelper_pkg.NewAPIError("HTTP Response Not OK" , _response.Code, _response.RawBody)
    }
    if(err != nil) {
        //error detected in status code validation
        return "", err
    }

    //returning the response
    return _response.Body, nil
}

/**
 * List All Inbound SMS in XML format
 * @param    *int64         page         parameter: Optional
 * @param    *int64         pagesize     parameter: Optional
 * @param    *string        from         parameter: Optional
 * @param    *string        to           parameter: Optional
 * @return	Returns the  response from the API call
 */
func (me *SMS_IMPL) CreateListInBoundSMSXML (
            page *int64,
            pagesize *int64,
            from *string,
            to *string) (error) {
        //the base uri for api requests
    _queryBuilder := testmessage360simpl2_lib.BASEURI;

    //prepare query string for API call
   _queryBuilder = _queryBuilder + "/sms/getInboundsms.xml"

    //variable to hold errors
    var err error = nil
    //validate and preprocess url
    _queryBuilder, err = apihelper_pkg.CleanUrl(_queryBuilder)
    if err != nil {
        //error in url validation or cleaning
        return err
    }

    //prepare headers for the outgoing request
    headers := map[string]interface{} {
        "user-agent" : "APIMATIC 2.0",
    }

    //form parameters
    parameters := map[string]interface{} {

        "page" : page,
        "pagesize" : pagesize,
        "from" : from,
        "to" : to,

    }


    //prepare API request
    _request := unirest.PostWithAuth(_queryBuilder, headers, parameters, testmessage360simpl2_lib.Config.AccountSid, testmessage360simpl2_lib.Config.AuthToken)
    //and invoke the API call request to fetch the response
    _response, err := unirest.AsString(_request);
    if err != nil {
        //error in API invocation
        return err
    }

    //error handling using HTTP status codes
    if (_response.Code < 200) || (_response.Code > 206) { //[200,206] = HTTP OK
        err = apihelper_pkg.NewAPIError("HTTP Response Not OK" , _response.Code, _response.RawBody)
    }
    if(err != nil) {
        //error detected in status code validation
        return err
    }

    //returning the response
    return nil
}

/**
 * List All Inbound SMS in JSON format
 * @param    *int64         page         parameter: Optional
 * @param    *string        pagesize     parameter: Optional
 * @param    *string        from         parameter: Optional
 * @param    *string        to           parameter: Optional
 * @return	Returns the string response from the API call
 */
func (me *SMS_IMPL) CreateListInBoundSMSJSON (
            page *int64,
            pagesize *string,
            from *string,
            to *string) (string, error) {
        //the base uri for api requests
    _queryBuilder := testmessage360simpl2_lib.BASEURI;

    //prepare query string for API call
   _queryBuilder = _queryBuilder + "/sms/getInboundsms.json"

    //variable to hold errors
    var err error = nil
    //validate and preprocess url
    _queryBuilder, err = apihelper_pkg.CleanUrl(_queryBuilder)
    if err != nil {
        //error in url validation or cleaning
        return "", err
    }

    //prepare headers for the outgoing request
    headers := map[string]interface{} {
        "user-agent" : "APIMATIC 2.0",
    }

    //form parameters
    parameters := map[string]interface{} {

        "page" : page,
        "pagesize" : pagesize,
        "from" : from,
        "to" : to,

    }


    //prepare API request
    _request := unirest.PostWithAuth(_queryBuilder, headers, parameters, testmessage360simpl2_lib.Config.AccountSid, testmessage360simpl2_lib.Config.AuthToken)
    //and invoke the API call request to fetch the response
    _response, err := unirest.AsString(_request);
    if err != nil {
        //error in API invocation
        return "", err
    }

    //error handling using HTTP status codes
    if (_response.Code < 200) || (_response.Code > 206) { //[200,206] = HTTP OK
        err = apihelper_pkg.NewAPIError("HTTP Response Not OK" , _response.Code, _response.RawBody)
    }
    if(err != nil) {
        //error detected in status code validation
        return "", err
    }

    //returning the response
    return _response.Body, nil
}

/**
 * List All SMS in XML format
 * @param    *int64         page         parameter: Optional
 * @param    *string        pagesize     parameter: Optional
 * @param    *string        from         parameter: Optional
 * @param    *string        to           parameter: Optional
 * @param    *string        datesent     parameter: Optional
 * @return	Returns the string response from the API call
 */
func (me *SMS_IMPL) CreateListSMSXML (
            page *int64,
            pagesize *string,
            from *string,
            to *string,
            datesent *string) (string, error) {
        //the base uri for api requests
    _queryBuilder := testmessage360simpl2_lib.BASEURI;

    //prepare query string for API call
   _queryBuilder = _queryBuilder + "/sms/listsms.xml"

    //variable to hold errors
    var err error = nil
    //validate and preprocess url
    _queryBuilder, err = apihelper_pkg.CleanUrl(_queryBuilder)
    if err != nil {
        //error in url validation or cleaning
        return "", err
    }

    //prepare headers for the outgoing request
    headers := map[string]interface{} {
        "user-agent" : "APIMATIC 2.0",
    }

    //form parameters
    parameters := map[string]interface{} {

        "page" : page,
        "pagesize" : pagesize,
        "from" : from,
        "to" : to,
        "datesent" : datesent,

    }


    //prepare API request
    _request := unirest.PostWithAuth(_queryBuilder, headers, parameters, testmessage360simpl2_lib.Config.AccountSid, testmessage360simpl2_lib.Config.AuthToken)
    //and invoke the API call request to fetch the response
    _response, err := unirest.AsString(_request);
    if err != nil {
        //error in API invocation
        return "", err
    }

    //error handling using HTTP status codes
    if (_response.Code < 200) || (_response.Code > 206) { //[200,206] = HTTP OK
        err = apihelper_pkg.NewAPIError("HTTP Response Not OK" , _response.Code, _response.RawBody)
    }
    if(err != nil) {
        //error detected in status code validation
        return "", err
    }

    //returning the response
    return _response.Body, nil
}

/**
 * List All SMS in JSON format
 * @param    *int64         page         parameter: Optional
 * @param    *int64         pagesize     parameter: Optional
 * @param    *string        from         parameter: Optional
 * @param    *string        to           parameter: Optional
 * @param    *string        datesent     parameter: Optional
 * @return	Returns the string response from the API call
 */
func (me *SMS_IMPL) CreateListSMSJSON (
            page *int64,
            pagesize *int64,
            from *string,
            to *string,
            datesent *string) (string, error) {
        //the base uri for api requests
    _queryBuilder := testmessage360simpl2_lib.BASEURI;

    //prepare query string for API call
   _queryBuilder = _queryBuilder + "/sms/listsms.json"

    //variable to hold errors
    var err error = nil
    //validate and preprocess url
    _queryBuilder, err = apihelper_pkg.CleanUrl(_queryBuilder)
    if err != nil {
        //error in url validation or cleaning
        return "", err
    }

    //prepare headers for the outgoing request
    headers := map[string]interface{} {
        "user-agent" : "APIMATIC 2.0",
    }

    //form parameters
    parameters := map[string]interface{} {

        "page" : page,
        "pagesize" : pagesize,
        "from" : from,
        "to" : to,
        "datesent" : datesent,

    }


    //prepare API request
    _request := unirest.PostWithAuth(_queryBuilder, headers, parameters, testmessage360simpl2_lib.Config.AccountSid, testmessage360simpl2_lib.Config.AuthToken)
    //and invoke the API call request to fetch the response
    _response, err := unirest.AsString(_request);
    if err != nil {
        //error in API invocation
        return "", err
    }

    //error handling using HTTP status codes
    if (_response.Code < 200) || (_response.Code > 206) { //[200,206] = HTTP OK
        err = apihelper_pkg.NewAPIError("HTTP Response Not OK" , _response.Code, _response.RawBody)
    }
    if(err != nil) {
        //error detected in status code validation
        return "", err
    }

    //returning the response
    return _response.Body, nil
}

/**
 * Send SMS through Message360 XML
 * @param    int64                            fromcountrycode           parameter: Required
 * @param    string                           from                      parameter: Required
 * @param    int64                            tocountrycode             parameter: Required
 * @param    string                           to                        parameter: Required
 * @param    string                           body                      parameter: Required
 * @param    models_pkg.HttpMethodEnum        method                    parameter: Optional
 * @param    *string                          messagestatuscallback     parameter: Optional
 * @return	Returns the string response from the API call
 */
func (me *SMS_IMPL) CreateSendSMSXML (
            fromcountrycode int64,
            from string,
            tocountrycode int64,
            to string,
            body string,
            method models_pkg.HttpMethodEnum,
            messagestatuscallback *string) (string, error) {
        //the base uri for api requests
    _queryBuilder := testmessage360simpl2_lib.BASEURI;

    //prepare query string for API call
   _queryBuilder = _queryBuilder + "/sms/sendsms.xml"

    //variable to hold errors
    var err error = nil
    //validate and preprocess url
    _queryBuilder, err = apihelper_pkg.CleanUrl(_queryBuilder)
    if err != nil {
        //error in url validation or cleaning
        return "", err
    }

    //prepare headers for the outgoing request
    headers := map[string]interface{} {
        "user-agent" : "APIMATIC 2.0",
    }

    //form parameters
    parameters := map[string]interface{} {

        "fromcountrycode" : fromcountrycode,
        "from" : from,
        "tocountrycode" : tocountrycode,
        "to" : to,
        "body" : body,
        "method" : models_pkg.HttpMethodEnumToValue(method),
        "messagestatuscallback" : messagestatuscallback,

    }


    //prepare API request
    _request := unirest.PostWithAuth(_queryBuilder, headers, parameters, testmessage360simpl2_lib.Config.AccountSid, testmessage360simpl2_lib.Config.AuthToken)
    //and invoke the API call request to fetch the response
    _response, err := unirest.AsString(_request);
    if err != nil {
        //error in API invocation
        return "", err
    }

    //error handling using HTTP status codes
    if (_response.Code < 200) || (_response.Code > 206) { //[200,206] = HTTP OK
        err = apihelper_pkg.NewAPIError("HTTP Response Not OK" , _response.Code, _response.RawBody)
    }
    if(err != nil) {
        //error detected in status code validation
        return "", err
    }

    //returning the response
    return _response.Body, nil
}

/**
 * Send SMS through Message360 Json
 * @param    int64                            fromcountrycode           parameter: Required
 * @param    string                           from                      parameter: Required
 * @param    int64                            tocountrycode             parameter: Required
 * @param    string                           to                        parameter: Required
 * @param    string                           body                      parameter: Required
 * @param    models_pkg.HttpMethodEnum        method                    parameter: Optional
 * @param    *string                          messagestatuscallback     parameter: Optional
 * @return	Returns the string response from the API call
 */
func (me *SMS_IMPL) CreateSendSMSJSON (
            fromcountrycode int64,
            from string,
            tocountrycode int64,
            to string,
            body string,
            method models_pkg.HttpMethodEnum,
            messagestatuscallback *string) (string, error) {
        //the base uri for api requests
    _queryBuilder := testmessage360simpl2_lib.BASEURI;

    //prepare query string for API call
   _queryBuilder = _queryBuilder + "/sms/sendsms.json"

    //variable to hold errors
    var err error = nil
    //validate and preprocess url
    _queryBuilder, err = apihelper_pkg.CleanUrl(_queryBuilder)
    if err != nil {
        //error in url validation or cleaning
        return "", err
    }

    //prepare headers for the outgoing request
    headers := map[string]interface{} {
        "user-agent" : "APIMATIC 2.0",
    }

    //form parameters
    parameters := map[string]interface{} {

        "fromcountrycode" : fromcountrycode,
        "from" : from,
        "tocountrycode" : tocountrycode,
        "to" : to,
        "body" : body,
        "method" : models_pkg.HttpMethodEnumToValue(method),
        "messagestatuscallback" : messagestatuscallback,

    }


    //prepare API request
    _request := unirest.PostWithAuth(_queryBuilder, headers, parameters, testmessage360simpl2_lib.Config.AccountSid, testmessage360simpl2_lib.Config.AuthToken)
    //and invoke the API call request to fetch the response
    _response, err := unirest.AsString(_request);
    if err != nil {
        //error in API invocation
        return "", err
    }

    //error handling using HTTP status codes
    if (_response.Code < 200) || (_response.Code > 206) { //[200,206] = HTTP OK
        err = apihelper_pkg.NewAPIError("HTTP Response Not OK" , _response.Code, _response.RawBody)
    }
    if(err != nil) {
        //error detected in status code validation
        return "", err
    }

    //returning the response
    return _response.Body, nil
}

