/*
 * testmessage360simpl2_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/03/2016
 */

package sms_pkg

import "testmessage360simpl2_lib/models_pkg"

/*
 * Interface for the SMS_IMPL
 */
type SMS interface {
    CreateViewSMSXML (string) (string, error)

    CreateViewSMSJSON (string) (string, error)

    CreateListInBoundSMSXML (*int64, *int64, *string, *string) (error)

    CreateListInBoundSMSJSON (*int64, *string, *string, *string) (string, error)

    CreateListSMSXML (*int64, *string, *string, *string, *string) (string, error)

    CreateListSMSJSON (*int64, *int64, *string, *string, *string) (string, error)

    CreateSendSMSXML (int64, string, int64, string, string, models_pkg.HttpMethodEnum, *string) (string, error)

    CreateSendSMSJSON (int64, string, int64, string, string, models_pkg.HttpMethodEnum, *string) (string, error)
}

/*
 * Factory for the SMS interaface returning SMS_IMPL
 */
func NewSMS() SMS {
    return &SMS_IMPL{}
}