/*
 * testmessage360simpl2_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/03/2016
 */

package call_pkg

import "testmessage360simpl2_lib/models_pkg"

/*
 * Interface for the CALL_IMPL
 */
type CALL interface {
    CreateViewCallXML (string) (string, error)

    CreateViewCallJSON (string) (string, error)

    CreateRecordCallXML (string, bool, models_pkg.DirectionEnum, *int64, *string, models_pkg.AudioFormatEnum) (string, error)

    CreateRecordCallJSON (string, bool, models_pkg.DirectionEnum, *int64, *string, models_pkg.AudioFormatEnum) (string, error)

    CreateVoiceEffectXML (string, models_pkg.AudioDirectionEnum, *float64, *float64, *float64, *float64, *float64) (string, error)

    CreateVoiceEffectJSON (string, models_pkg.AudioDirectionEnum, *float64, *float64, *float64, *float64, *float64) (string, error)

    CreatePlayAudioXML (string, string, *int64, models_pkg.DirectionEnum, *bool, *bool) (string, error)

    CreatePlayAudioJSON (int64, models_pkg.DirectionEnum, bool, bool, *string, *string) (string, error)

    CreateListCallXML (*string, *string, *string, *string, *string) (string, error)

    CreateListCallJSON (*string, *string, *string, *string, *string) (error)

    CreateInterruptedCallJSON (string, *string, models_pkg.HttpMethodEnum, models_pkg.InterruptedCallStatusEnum) (string, error)

    CreateSendDigitJSON (string, string, models_pkg.DirectionEnum) (string, error)

    CreateInterruptedCallXML (string, *string, models_pkg.HttpMethodEnum, models_pkg.InterruptedCallStatusEnum) (string, error)

    CreateSendDigitXML (string, string, models_pkg.DirectionEnum) (string, error)

    CreateMakeCallXML (models_pkg.HttpMethodEnum, string, models_pkg.HttpMethodEnum, string, models_pkg.HttpMethodEnum, string, models_pkg.HttpMethodEnum, int64, string, bool, bool, string, models_pkg.HttpMethodEnum, bool, string, models_pkg.IfMachineEnum, *string, *string, *string, *string, *string) (string, error)

    CreateMakeCallJSON (string, string, string, string, string, models_pkg.HttpMethodEnum, *string, models_pkg.HttpMethodEnum, *string, models_pkg.HttpMethodEnum, *string, *bool, *int64, *string, *bool, *bool, *string, models_pkg.HttpMethodEnum, *bool, *string, models_pkg.IfMachineEnum) (string, error)
}

/*
 * Factory for the CALL interaface returning CALL_IMPL
 */
func NewCALL() CALL {
    return &CALL_IMPL{}
}