/*
 * testmessage360simpl2_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/03/2016
 */

package carrier_pkg


/*
 * Interface for the CARRIER_IMPL
 */
type CARRIER interface {
    CreateCarrierLookupXML (string) (string, error)

    CreateCarrierLookupJSON (string) (string, error)

    CreateCarrierLookupListXML (*string, *string) (string, error)

    CreateCarrierLookupListJSON (*string, *string) (string, error)
}

/*
 * Factory for the CARRIER interaface returning CARRIER_IMPL
 */
func NewCARRIER() CARRIER {
    return &CARRIER_IMPL{}
}