/*
 * testmessage360simpl2_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/03/2016
 */

package conference_pkg

import "testmessage360simpl2_lib/models_pkg"

/*
 * Interface for the CONFERENCE_IMPL
 */
type CONFERENCE interface {
    CreateViewConferenceJSON (string) (string, error)

    CreateViewConferenceXML (string) (string, error)

    CreateViewParticipantJSON (string, string) (string, error)

    CreateViewParticipantXML (string, string) (string, error)

    CreateListConferenceJSON (*int64, *int64, *string, models_pkg.InterruptedCallStatusEnum, *string, *string) (string, error)

    CreateListConferenceXML (*int64, *int64, *string, models_pkg.InterruptedCallStatusEnum, *string, *string) (string, error)

    AddParticipantJSON (string, string, int64, *bool, *bool) (string, error)

    AddParticipantXML (string, string, int64, *bool, *bool) (string, error)

    CreateListParticipantJSON (string, *int64, *int64, *bool, *bool) (string, error)

    CreateListParticipantXML (string, *int64, *int64, *bool, *bool) (string, error)
}

/*
 * Factory for the CONFERENCE interaface returning CONFERENCE_IMPL
 */
func NewCONFERENCE() CONFERENCE {
    return &CONFERENCE_IMPL{}
}