/*
 * testmessage360simpl2_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/03/2016
 */

package testmessage360simpl2_lib

/** The base Uri for API calls */
const BASEURI string = "https://api.message360.com/api/v2"

var Config struct {
    /** Account sid for authentication */
    /** Replace the value of AccountSid with an appropriate value */
    AccountSid string
    /** Auth token for authentication  */
    /** Replace the value of AuthToken with an appropriate value */
    AuthToken string
}
